# Generated by Django 3.2 on 2021-10-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='corrected_data_by_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_tab_name', models.CharField(max_length=150)),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='data_given_by_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='detailquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10)),
                ('dest', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=6)),
                ('Email', models.EmailField(max_length=254)),
                ('comments', models.TextField()),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='feeback_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('comments', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='gonikoppal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='incorrect_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_tab_name', models.CharField(max_length=20)),
                ('post_id', models.IntegerField()),
                ('complaint', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kodagu_town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Town_name', models.CharField(max_length=150)),
                ('use', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='kutta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='liked_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Madikeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='madikeri2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='murnad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Napoklu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ponnampet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='replys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_comenter', models.IntegerField()),
                ('reply', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='save_contact_inf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('comments', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='somarpet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Travel_exprience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('likes', models.IntegerField()),
                ('Dislikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='virajpet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Middle_route', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('arrive_t', models.TimeField()),
                ('leave_t', models.TimeField()),
                ('Busname', models.CharField(max_length=150)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
    ]
